// Vuetify Documentation https://vuetifyjs.com

import Vue from 'vue'
import Vuetify from 'vuetify/lib/framework'
import VueI18n from 'vue-i18n'

import {
  VCol,
  VRow,
} from 'vuetify/lib'

Vue.use(Vuetify)
Vue.use(VueI18n)
Vue.use({
  components: {
    VCol,
    VRow,
  },
})

const messages = {
  en: {
    $vuetify: {
      header: {
        Home: 'Home',
        Whitepaper: 'Whitepaper',
        FAQ: 'FAQ',
        Vision: 'Vision',
        Charities: 'Charities',
        Roadmap: 'Roadmap',
        Team: 'Team',
      },
      hero: {
        title: 'Crypto for animals.',
        slogan: 'AFU gives purpose to crypto investments and promotes efficient animal and species protection.',
        button1: 'Join our Telegram',
        textbetween: 'and',
        button2: 'Buy $AFU (soon)',
      },
      vision: {
        title: 'The $AFU Vision',
        text: 'Everyone loves animals. Yet there is still far too much animal suffering all over the world. Every wild animal deserves freedom and protection from humans, every farm animal and domestic animal deserves species-appropriate keeping, which reminds of the animals\' original natural living conditions. With $AFU, we give finally a sense to the speculation money put on in Krypto by promoting animal protection.',
        item1: 'Useful',
        item1text: 'We combine crypto investments with animal protection and thereby give them a purpose. And we reward those who contribute.',
        item2: 'Holistic',
        item2text: 'In our understanding, species protection and animal welfare are parts of a big whole. Therefore we cover all areas.',
        item3: 'Transparent',
        item3text: 'We show transparently which charities we work with. So you can form your own picture and donate there what appeals to you the most.',
        item4: 'High Quality',
        item4text: 'All the charities we work with are carefully screened by AFU Team and are only selected after a positive outcome.',
        item5: 'Open-minded',
        item5text: 'We believe in the bottom-up approach. In every step forward, we listen to our animal friends and we are happy about every suggestions!',
        item6: 'United',
        item6text: 'We all share our core values of bringing purpose into crypto world and making the world a better place by helping animals.',
      },
      animals: {
        title: 'ANIMAL AND SPECIES PROTECTION',
        item1: 'Pets',
        item1text: 'Stray dogs and cats are a sad reality in most countries of the world. We humans have domesticated some species and are therefore responsible for the well-being of these animals.',
        item2: 'Wildlife',
        item2text: 'We focus on highly endangered or endangered species and promote specific conservation measures such as the expansion of natural habitats to preserve and promote biodiversity.',
        item3: 'Livestock',
        item3text: 'No animal should be tortured in agriculture, in laboratories or anywhere else. Housing conditions must be improved and meat consumption must be made possible without killing animals.',
      },
      services: {
        title: 'AFU FOR CHARITIES',
        item1: 'New donators',
        item1slogan: 'Reach new channels',
        item1text: 'Bring the liquid cryptocurrency market into your charity and reach a greater range of animal friends.',
        item2: 'Easy setup',
        item2slogan: 'Done in 5 minutes',
        item2text: 'Download a wallet app for iOS/Android/Chrome and copy your crypto address to start getting donations.',
        item3: '100% free',
        item3slogan: 'No costs involved',
        item3text: 'You can reach our animal friends from cryptocurrency space completely for free - without any setup/running costs.',
        item4: 'More income',
        item4slogan: 'Get more out of it',
        item4text: 'Increase the $AFU donations received through token price increases and our wallet storing rewards.',
        item5: 'AFU Services',
        item5slogan: 'Advertisement, Reviews',
        item5text: 'Pay the AFU team with your $AFU for advertisement and review services to improve your service and reach more people.',
        item6: 'Gold Partner',
        item6slogan: 'Larger reach',
        item6text: 'Become AFU gold partner through holding tokens on your wallet and have a strong presence on all of our channels.',
        item7: 'Strong networking',
        item7slogan: 'Coming soon',
        item7text: 'Get access to our charity network and contact data to do joint fundings in AFU and build synergies with partners.',
        item8: 'Shop Integration',
        item8slogan: 'Coming soon',
        item8text: 'Integrate $AFU in your shop easily through a plugin and directly sell your merchandise to the crypto animal friends.',
      },
      contact: {
        title: 'Time to get involved in Crypto!',
        text: 'Contact the AFU Team, join our network and start receiving crypto donations now.',
        button: 'Contact our team',
      },
      roadmap: {
        title: 'Roadmap',
        item1: 'Project Launch',
        item1text: 'Formation of the company and core team, planning of the next steps.',
        item2: 'Website and Whitepaper',
        item2text: 'The website with details on the project and the token is live. First Whitepaper version with all details on tokenomics is released.',
        item3: 'Exchange listing',
        item3text: '$AFU will be buyable on the first exchange. The token will also be listed on major crypto raking pages.',
        item4: 'Donation voting & token burning',
        item4text: 'The monthly tokenholder voting for the allocation of the donations and token burning will be introduced.',
        item5: 'Charity partnerships',
        item5text: 'Multiple charity partnerships are revealed and charity program is launched.',
        item6: 'Shop integration',
        item6text: 'Shop plugin for charity online shops will be launched to pay with $AFU.',
        item7: 'AFU services',
        item7text: 'We will launch our exclusive services for Charities, paid with $AFU.',
      },
      socialmedia: {
        title: 'Social Media',
        text: 'Follow us on twitter for the latest #AFU news and updates.',
        button: 'Follow @AFU_Project',
      },
      team: {
        title: 'The $AFU Vision',
        item1: 'Founder',
        item1text: 'Business economist with professional experience in the electronics sector. Famous crypto influencer known as "TheCryptoCandy" since 2018. Has helped numerous projects and exchanges like OKEx and Bittrex to grow.',
        item2: 'Co-Founder, Legal',
        item2text: 'Freelance advisor to SMEs and start-ups for over 10 years with a focus on strategy consulting and digital transformation along the entire value chain. Active in the field of blockchain and crypto since 2019.',
        item3: 'Co-Founder, IT & Business Dev.',
        item3text: 'Experienced consultant, developer and IT project manager in several international corporations. Has had multiple positions in various crypto projects, Community Lead at ZelaaPayAE since 2020, known as "mazelaa".',
      },
      faq: {
        cat1: 'Token',
        cat2: 'Other',
        q1: 'What is the fair value of $AFU?',
        a1: '$AFU is a utility token. $AFU is a utility token. Therefore the value can not be calculated directly as for example with shares. There are even many tokens that are worth many hundreds of millions of dollars without a use case - the value in these examples is given by the use of the community alone. $AFU has clear utilities and is working on animal welfare worldwide. If $AFU can establish itself as a donation platform in the crypto sector and a single percent is shifted from the ten largest crypto currencies to AFU, this would result in a market capitalization of $AFU of <strong>$2.8 billion</strong>, which corresponds to a token price of $35 at 80M CS.',
        q2: 'Why is $AFU an ERC-10 token?',
        a2: 'For the current use cases the TRC-10 token is sufficient. But we are blockchain-agnostic and reserve the right - if reasonable and necessary - to migrate the token to TRC-20 or another network.',
        q3: 'Do you already have charities that are participating or that you are in discussion?',
        a3: 'We already have trusted charities that are working with us and we are in discussion with many others. If you know a trustworthy animal welfare organization that you would like to see engaged with $AFU and that deserves getting more donations, please send us a message with your suggestion or contacts.',
      },
      whitepaper: {
        disclaimer: '<h2>Whitepaper Version</h2>Whitepaper 1.0 (07.10.2020).<br><br><h2>Disclaimer</h2>This document is a whitepaper representing current and future developments of AFU. This whitepaper is for information purpose only and should not be considered as an exact guiding document depicting all future intent of AFU platform, unless specified explicitly. AFU makes no representations or warranties for successful implementation or development of such technologies, innovation and platform or achievement of any other implementation or activities illustrated in the paper. It further disclaims all the warranties implied by any law or legal authorities to the extent permitted by law. No person or company is entitled to rely on the content and promises illustrated in this paper or any other inferences drawn from it, which includes relation to any interactions with AFU or the technologies elaborated in this whitepaper. The information present in this publication is derived from data obtained through the sources which are believed by AFU to be reliable and is presented in good faith and forecasted as AFU strongly believes in it, but with no warranties or guarantees. Contents of this paper regarding accuracy, completeness or suitability of the information specified, are as per the sources available at the time of its drafting and should be not relied on and shall not confer remedies or rights upon, by holders of security, creditors or other equity holders or any other person.<br><br>AFU disclaims all the liability for any damage or loss of capital, interest or property of any kind (whether foreseeable or not) which may arise from any company or person acting on any information and opinions relating to AFU contained in this paper or any other information presented regarding any further inquiries. The information in this Whitepaper may change without any prior notice. AFU does not have any constraint to update, modify or ameliorate any projection, forecast, opinion or estimate set forth, or subsequent changes which makes the data inaccurate. AFU and it\'s employees or representatives do not have any liability or responsibility to any recipient or person (whether by the negligence of misstatement or by reason). AFU does not independently take any guarantee of the information including projection, prospects, and forecasts presented in this whitepaper. Each recipient or person is to rely solely on its own investigation, knowledge, assessment and judgment of the matter which is subject of this publication and any other information which is made available via further inquiries or to satisfy the accuracy of projections. Whilst AFU has made every effort to ensure the authenticity of the facts and forecasts made in this whitepaper. Any forecast, projections or plans mentioned in this whitepaper publication may not be achieved due to several risk factors like market volatility, legal or regulatory exposure, corporate actions, defects in technology development, unavailability of information and all other risks. AFU may provide website’s hyperlinks of entities present in this whitepaper, though the inclusion of any link does not imply that AFU recommends, endorses or approves any material on the linked website. Such linked websites should be solely accessed by your own risk and AFU does not accept any responsibility for any such material or consequences of it. This whitepaper is only available on www.afuproject.com and may not be reproduced, redistributed or passed on to any other entity. The distribution of this whitepaper may be restricted by regulations or law in certain countries. By accessing this whitepaper publication, the recipient agrees to be bound with foregoing limitations.',
        summary: 'The project AFU was initiated, since up to now no crypto project which combines the profit aspect of crypto with the charitable idea could be established. AFU was created by great animal friends and sat down to the goal of bringing crypto money into the protection of animals and species.<br><br><h2>Use Cases</h2><ul><li>AFU promotes animal protection - and the value of the token - primarily by direct donations and the monthly donation voting the animal protection.</li><li>50% of the tokens received over the voting are burned directly. The other 50% go into the charity pool to ensure its sustainability. The pool is used for the monthly donations. 1% of the pool is being donated every month according to the donation voting ratio.</li><li>Our AFU services (e.g. advertising), which we offer to charities, can only be paid with $AFU.</li><li>The purchase of the token alone indirectly promotes animal welfare by giving the donations received a higher value. The intended growth of the token value as well as the careful selection and cooperation with our partners leads to a longer holding period of the received donations in $AFU.</li><li>AFU also rewards the most important donors with goodies (in preparation).</li></ul><br>In addition to the increase in value, the <strong> expectation of an increase in value of the token should also be created. On the one hand, this creates incentives for the charities not to sell their tokens directly after receipt of money. On the other hand, it offers the possibility to substantially increase the amount of donations received by holding the tokens - at least for longer holding periods. A sustainable high AFU pool is also ensured by the AFU Services.',
        situationTitle: 'Situation',
        situation: '<h2>Key figures</h2><ul><li>There are no global statistics on total donations. The sum over the leading world economies shows that the total volume is at least several hundred billion dollars annually.</li><li>In 2019, the total sum of donations worldwide has increased by 4.1% compared to the previous year. Online donations have even increased by 12.1%.</li><li>Millenials already use the online channel for donations the most. A particularly strong growth can be seen in mobile donations. In the context of online donations, donations in the environmental area are growing particularly strongly.</li></ul><a href="https://doublethedonation.com/tips/matching-grant-resources/nonprofit-fundraising-statistics/">Source</a><br><br><h2>Additional facts</h2><ul><li>Millenials are defined as the most socially responsible consumers to whom responsible behavior is very important. This is why the social aspect plays a particularly important role for the Millenials.</li><li>Millenials are less interested in the people or the ideas behind a nonprofit organization than in the results that the nonprofit organization produces. Tangible results are important.</li><li>Content marketing, mainly through blogging and social media contributions, is an important way for organizations to engage with their communities and increase their online visibility.</li><li>The online channel is especially important for small and medium sized charities that are not yet well known. </li></ul><a href="https://www.nptechforgood.com/2018/03/20/10-must-know-stats-about-online-fundraising/">Source</a><br><br><h2>Current developments</h2><ul><li><strong>Mobile donations</strong>: Already explained above</li><li><strong>Micro donations</strong>: Represent an important trend in the donations market. If a small donation can be made quickly and easily, millenials in particular are much more willing to donate than if a longer form has to be filled out first. With micro donations, the tax aspect also hardly plays a role (<a href="https://non-profit. today/micro-donations/">Source</a>)</li></ul><br><h2>Problemstellungen</h2>AFU would like to address and solve the following problems:<ul><li><strong>Donations from the crypto market</strong>: Although many investors have already earned a lot of money with Bitcoin and other crypto currencies and many Millenials are active in the crypto market, hardly anything is donated from the crypto market today. The willingness to donate a small part of one\'s own profits for a good cause is there, but there are no easy ways, which have become established in the market, to donate efficiently and effectively.</li><li><strong>Lack of transparency</strongA: What do the organizations really do with the money? Which ones are trustworthy and really achieve something?</li><li><strong>Lack of time</strong>: People who want to help but don\'t have the time to donate. Time is something you can\'t get back and especially Millenials always have too little time.</li><li><strong>Short-term lack of donations</strong>: 2020 was also a highly exceptional and challenging year for many charities. Short-term donation collapses require new channels and solutions.</li></ul>',
        approachTitle: 'Approach',
        approach: '<h2>Vision</h2>The potential in the cryptomarket for the support of animal and species protection should be fully exploited. Charity and profit should no longer be opposites, but work hand in hand.<br><br><h2>Mission</h2>The potential for donations to charitable organizations for the purpose of animal and species protection, which is available in the crypto market, should flow into AFU and be passed on there directly or indirectly to audited organizations. The organizations should have incentives not to sell the $AFU Tokens immediately after receipt of money but to keep them. The token price should increase sustainably to increase the donations received, so that even more money is available for the organizations. The received donations should only be given to those organizations zuflieẞen, which have a minimal administration effort, so that most of the money goes directly to the animals.<br><br>Our values, with which we pursue our mission together with the AFU Community, are described in more detail on the homepage.<br><br><h2>Target group</h2>Our main target group are Millenials. Preferred are Millenials, who already made an investment in a crypto currency or who know the crypto market.<br><br>Donors, who have nothing to do with the crypto market, will continue to donate directly to Fiat charities. We would like to move existing crypto assets to more animal protection and do not see it as our task to move Fiat money into the crypto market. Accordingly our marketing efforts are focused on the crypto sector.<br><br><h2>USP</h2> <ul> <li>For existing participants in the crypto market we offer a <strong>very simple solution</strong> to donate a part of the profits with extremely low effort and costs to a <strong> certified charity</strong> and thereby directly support animals. Investors who are not interested in making a donation can still help to increase the value of the donations by purchasing $AFU. <In this way, animal aid goes hand in hand with the profit motive of the investors. FOOD offers the possibility of strong micro-donations. By building on the TRON network, there are no significant fees, so that $AFU is also ideally suited for micro-donations. In addition to direct donations, AFU offers investors the possibility of a monthly voting. The assets, which the AFU team distributes monthly from the pool, are distributed to the partner organizations according to the voting. We believe in the bottom-up approach and therefore involve our community in this important decision.</li><li>Our team actively encourages the charities to keep $AFU on the wallet instead of immediately selling the donations received. This is supported by strong FOOD services such as advertising for charities, which can be paid for with $FOOD at ausschlieẞlich. In addition the received donation contributions can be increased in expectation of a price increase of the AFU token <strong> by holding it.</li></ul><br>By our strong presence and cross-linking in the crypto market as well as in the Charity market we protect ourselves against copies.',
        utilities: 'The following are the most important Use Cases of $AFU:<br><br><ul><li><strong> Direct Donations</strong>: Donate directly to the animal and species protection organizations audited by us without a middleman.</li><li><strong>Donation Voting</strong>: AFU donates a significant amount of money from the AFU pool to the animal protection organizations every month. Tokenholders can support the favored organization by a payment of AFU into the pool and so influence the ratio of the donated total amount in favor of the selected organizations.</li><li><strong>Token burning</strong>: 50% of the tokens transferred monthly for the voting are burned after the payment of the monthly donation to the charities. The regular token burning supports the growth of the token value and leads to higher donation amounts and an increase in the donations received.</li><li><strong>Token buying</strong>: The higher the market capitalization of our crypto currency, the higher the donated contributions, which are distributed by the charities affiliated to us. Accordingly each purchase of AFU makes a contribution to animal and species protection.</li><li><strong>AFU Services</strong>: In relation to the Charities we offer our AFU services such as advertising campaigns, which can be paid only with $AFU.</li></ul><br> The gröẞten donors receive auẞerdem small Goodies (more information in addition follows).',
        tokenomics: '<h2>Value and network</h2>$AFU is a utility token. The fair value can therefore not be calculated directly and is determined by the market. $AFU is a TRC-10 token, but we are blockchain-agnostic and reserve the right - if reasonable and necessary - to migrate the token to TRC-20 or to another network. For the current use cases the TRC-10 token is sufficient.<br><br><h2>Locked tokens</h2>15M tokens are locked in the charity pool and are only distributed towards charities according to the use cases described above. 10M tokens were locked as an additional direct long-term incentive for the team to achieve a higher token price. Of these, 5M are locked until April 1, 2021 and another 5M until October 1, 2021.<br><br><h2>Token distribution</h2>Before the first exchange listing, tokens were distributed through OTC deals (invite-only) for the price of 1 AFU = 1 TRX. Besides the 10M locked tokens for the team, the team members had to buy the token. Except for small giveaways with a total volume of less than 50000 tokens, no tokens were given away for free. The funds raised are used for development, marketing, exchange listings and business growth.',
      },
      footer: {
        section1: '$AFU Project',
        section1text: 'The AFU Team has committed itself to the goal of not only preserving the protection of species and animals at the current level, but improving it. For crypto investors, AFU supplements the monetary aspect with the simultaneous promotion of nature and animal protection.',
        section1button: 'Whitepaper',
        section2: 'Links (coming soon)',
        section2item1: 'Buy $AFU',
        section2item2: 'CoinMarketCap',
        section2item3: 'Coingecko',
        section2item4: 'Whitepaper',
        section2item5: 'Imprint',
        section3: 'Imprint',
        section3text: 'Sebastian Wolf AFU<br />Hornstr. 8<br />54294 Trier<br />Germany',
        section3mails: 'hello@afuproject.com<br>business@afuproject.com',
        copyright: 'All rights reserved &copy; 2020 Sebastian Wolf AFU',
      },
    },
  },
  de: {
    $vuetify: {
      header: {
        Home: 'Home',
        Whitepaper: 'Whitepaper',
        FAQ: 'FAQ',
        Vision: 'Vision',
        Charities: 'Charities',
        Roadmap: 'Roadmap',
        Team: 'Team',
      },
      hero: {
        title: 'Krypto für Tiere.',
        slogan: 'AFU gibt Kryptoinvestitionen einen Sinn und fördert den effizienten Tier- und Artenschutz.',
        button1: 'Auf Telegram mitdiskutieren',
        textbetween: 'und',
        button2: '$AFU kaufen (bald)',
      },
      vision: {
        title: 'Die $AFU Vision',
        text: 'Jede/r liebt Tiere. Dennoch gibt es immer noch viel zu viel Tierleid auf der ganzen Welt. Jedes Wildtier verdient Freiheit und Schutz durch den Menschen, jedes Nutz- und Haustier verdient eine artgerechte Haltung, die an die ursprünglichen natürlichen Lebensbedingungen der Tiere erinnert. Mit $AFU geben wir dem in Krypto angelegten Spekulationsgeld endlich einen Sinn, indem wir den Tierschutz fördern.',
        item1: 'Sinnvoll',
        item1text: 'Wir verbinden Krypto-Investitionen mit Tierschutz und geben ihnen damit einen Sinn. Und wir belohnen diejenigen, die dazu beitragen.',
        item2: 'Ganzheitlich',
        item2text: 'Nach unserem Verständnis sind Arten- und Tierschutz Teile eines großen Ganzen. Deshalb decken wir alle Bereiche ab.',
        item3: 'Transparent',
        item3text: 'Wir zeigen transparent, mit welchen Wohltätigkeitsorganisationen wir zusammenarbeiten. So können Sie sich ein eigenes Bild machen und dort spenden, was Ihnen am meisten zusagt.',
        item4: 'Hochwertig',
        item4text: 'Alle Wohltätigkeitsorganisationen, mit denen wir zusammenarbeiten, werden vom AFU-Team sorgfältig geprüft und erst nach einem positiven Ergebnis ausgewählt.',
        item5: 'Aufgeschlossen',
        item5text: 'Wir glauben an den Bottom-up-Ansatz. Bei jedem Schritt vorwärts hören wir auf unsere Tierfreunde und freuen uns über jeden Vorschlag!',
        item6: 'Vereint',
        item6text: 'Wir alle teilen unsere Grundwerte, die darin bestehen, Sinn in die Krypto-Welt zu bringen und die Welt durch Tierschutz und Tierhilfe zu einem besseren Ort zu machen.',
      },
      animals: {
        title: 'Tier- und Artenschutz',
        item1: 'Haustiere',
        item1text: 'Streunende Hunde und Katzen sind in den meisten Ländern der Welt eine traurige Realität. Wir Menschen haben einige Arten domestiziert und sind daher für das Wohlergehen dieser Tiere verantwortlich.',
        item2: 'Wildtiere',
        item2text: 'Wir konzentrieren uns auf stark gefährdete oder vom Aussterben bedrohte Arten und fördern spezifische Erhaltungsmaßnahmen wie die Ausweitung natürlicher Lebensräume, um die biologische Vielfalt zu erhalten und zu fördern.',
        item3: 'Nutztiere',
        item3text: 'Kein Tier sollte in der Landwirtschaft, in Laboratorien oder anderswo gequält werden. Die Haltungsbedingungen müssen verbessert und der Fleischkonsum ohne Tötung der Tiere ermöglicht werden.',
      },
      services: {
        title: 'AFU für Charities',
        item1: 'Neue Spender',
        item1slogan: 'Neue Kanäle erreichen',
        item1text: 'Bringen Sie den flüssigen Kryptomarkt in Ihre Wohltätigkeitsorganisation ein und erreichen Sie eine größere Anzahl von Tierfreunden.',
        item2: 'Einfacher Start',
        item2slogan: 'Erledigt in 5 Minuten',
        item2text: 'Laden Sie eine Wallet-App für iOS/Android/Chrome herunter und kopieren Sie Ihre Krypto-Adresse, um Spenden zu erhalten.',
        item3: '100% kostenlos',
        item3slogan: 'Keine Investitionskosten',
        item3text: 'Sie können unsere Tierfreunde aus dem Krypto-Währungsraum völlig kostenlos erreichen - ohne jegliche Einrichtungs- und Betriebskosten.',
        item4: 'Mehr Einkommen',
        item4slogan: 'Mehr draus machen',
        item4text: 'Vermehren Sie die erhaltenen $AFU-Spenden durch Wachstum des Tokenpreises sowie die Aufbewahrungsbelohnungen.',
        item5: 'AFU Services',
        item5slogan: 'Werbung, Reviews',
        item5text: 'Bezahlen Sie das AFU-Team mit Ihren $AFU für Werbe- und Überprüfungsdienste, um Ihren Service zu verbessern und mehr Menschen zu erreichen.',
        item6: 'Gold Partner',
        item6slogan: 'Größere Reichweite',
        item6text: 'Werden Sie AFU-Goldpartner, indem Sie Wertmarken in Ihrer Brieftasche halten und erhalten Sie eine starke Präsenz auf allen unseren Kanälen.',
        item7: 'Starkes Networking',
        item7slogan: 'Bald',
        item7text: 'Erhalten Sie Zugang zu unserem Wohltätigkeitsnetzwerk und Kontaktdaten, um gemeinsam in der AFU zu finanzieren und Synergien mit Partnern aufzubauen.',
        item8: 'Shop Integration',
        item8slogan: 'Bald',
        item8text: 'Integrieren Sie $AFU einfach über ein Plugin in Ihren Shop und verkaufen Sie Ihre Waren direkt an die Krypto-Tierfreunde.',
      },
      contact: {
        title: 'Zeit, bei Krypto mitzumachen!',
        text: 'Kontaktieren Sie das AFU-Team, treten Sie unserem Netzwerk bei und beginnen Sie jetzt mit dem Empfang von Kryptospenden.',
        button: 'Team kontaktieren',
      },
      roadmap: {
        title: 'Roadmap',
        item1: 'Projekt-Start',
        item1text: 'Bildung des Unternehmens und des Kernteams, Planung der nächsten Schritte.',
        item2: 'Website und Whitepaper',
        item2text: 'Die Website mit Einzelheiten über das Projekt und den Token ist live. Die erste Whitepaper-Version mit allen Details zu Tokenomics ist veröffentlicht.',
        item3: 'Exchange listing',
        item3text: '$AFU wird bei der ersten Exchange kaufbar sein. Der Token wird auch auf den grossen Kryptorankingseiten aufgeführt werden.',
        item4: 'Donation Voting & Token burning',
        item4text: 'Das monatliche Tokenholder Voting für die Verteilung der Spenden sowie das Token Burning wird eingeführt.',
        item5: 'Charity Partnerschaften',
        item5text: 'Mehrere Wohltätigkeitspartnerschaften werden veröffentlicht und das Vernetzungsprogramm wird gestartet.',
        item6: 'Shop integration',
        item6text: 'Shop-Plugin für Wohltätigkeits-Onlineshops wird eingeführt, um mit $AFU zu bezahlen.',
        item7: 'AFU services',
        item7text: 'Wir werden unsere exklusiven Dienstleistungen für Wohltätigkeitsorganisationen einführen, die mit $AFU bezahlt werden.',
      },
      socialmedia: {
        title: 'Social Media',
        text: 'Folgen Sie uns auf Twitter für die neuesten #AFU-Nachrichten und Updates.',
        button: 'Folgen Sie @AFU_Project',
      },
      team: {
        title: 'Die $AFU Vision',
        item1: 'Founder',
        item1text: 'Betriebswirtschaftlerin mit Berufserfahrung in der Elektronikbranche. Berühmte Crypto Influencerin, seit 2018 unter dem Namen "TheCryptoCandy" bekannt. Hat zahlreichen Projekten und Börsen wie OKEx und Bittrex zum Wachstum verholfen.',
        item2: 'Co-Founder, Legal',
        item2text: 'Freiberuflicher Berater von KMUs und Start-ups seit über 10 Jahren mit Schwerpunkt auf Strategieberatung und digitaler Transformation entlang der gesamten Wertschöpfungskette. Seit 2019 im Bereich Blockchain und Crypto tätig.',
        item3: 'Co-Founder, IT & Business Dev.',
        item3text: 'Erfahrener Berater, Entwickler und IT-Projektmanager in mehreren internationalen Unternehmen. War in verschiedenen Kryptoprojekten involviert, seit 2020 Community Lead bei ZelaaPayAE, bekannt als "mazelaa".',
      },
      faq: {
        cat1: 'Token',
        cat2: 'Anderes',
        q1: 'Was ist die richtige Bewertung von $AFU?',
        a1: '$AFU ist ein Utility Token. Daher kann der Wert nicht direkt berechnet werden, wie beispielsweise bei Aktien. Es gibt sogar viele Tokens, die ohne einen real existierenden Use Case viele Hunderte von Millionen Dollar wert sind - der Wert in diesen Beispielen ergibt sich allein aus der Nutzung durch die Gemeinschaft oder durch Spekulation. $AFU hat klare Use Cases. Es gibt sogar viele Wertmarken, die ohne einen Anwendungsfall viele hundert Millionen Dollar wert sind - der Wert in diesen Beispielen ergibt sich allein aus der Nutzung durch die Gemeinschaft. $AFU hat klare Nutzen und setzt sich weltweit für den Tier- und Artenschutz ein. Wenn sich $AFU als Spendenplattform im Kryptobereich etablieren kann und ein einziges Prozent aus den zehn grössten Kryptowährungen in AFU verschoben wird, ergäbe dies eine Marktkapitalisierung von $AFU von <strong>$2.8 Milliarden</strong>, was bei 80M CS einem Tokenpreis von 35$ entspricht.',
        q2: 'Warum ist $AFU ein TRC-10 Token?',
        a2: 'Für die aktuellen Anwendungsfälle ist der TRC-10-Token ausreichend. Wir sind jedoch blockchain-agnostisch und behalten uns das Recht vor - falls sinnvoll und notwendig - den Token auf TRC-20 oder ein anderes Netzwerk zu migrieren',
        q3: 'Sind Charities bereits im Projekt involviert oder sind diese noch in Diskussion?',
        a3: 'Wir haben bereits vertrauenswürdige Wohltätigkeitsorganisationen, die mit uns zusammenarbeiten, und wir sind mit vielen anderen im Gespräch. Wenn du eine vertrauenswürdige Tierschutzorganisation kennst, die es verdient, mehr Spenden zu erhalten, sende uns bitte eine Nachricht mit deinem Vorschlag oder deinen Kontakten.',
},
      whitepaper: {
        disclaimer: '<h2>Whitepaper Version</h2>Whitepaper 1.0 (07.10.2020).<br><br><h2>Disclaimer</h2>Bei diesem Dokument handelt es sich um ein Whitepaper, das aktuelle und zukünftige Entwicklungen der AFU darstellt. Dieses Whitepaper dient nur zu Informationszwecken und sollte nicht als genaues Leitdokument betrachtet werden, das alle zukünftigen Absichten der AFU-Plattform darstellt, es sei denn, dies wird ausdrücklich angegeben. AFU gibt keine Zusicherungen oder Gewährleistungen für die erfolgreiche Implementierung oder Entwicklung solcher Technologien, Innovationen und Plattformen oder für das Erreichen anderer Implementierungen oder Aktivitäten, die in dem Papier dargestellt werden. AFU lehnt ferner alle Gewährleistungen ab, die von einem Gesetz oder einer Rechtsbehörde impliziert werden, soweit dies gesetzlich zulässig ist. Keine Person oder Firma ist berechtigt, sich auf den Inhalt und die Versprechungen, die in diesem Papier illustriert sind, oder auf andere daraus gezogene Schlüsse zu verlassen, was auch die Beziehung zu jeglichen Interaktionen mit der AFU oder den in diesem Whitepaper ausgearbeiteten Technologien einschließt. Die in dieser Publikation enthaltenen Informationen stammen aus Daten, die aus Quellen gewonnen wurden, die von der AFU als zuverlässig erachtet werden, und werden in gutem Glauben präsentiert und so prognostiziert, wie AFU fest daran glaubt, jedoch ohne Gewährleistungen oder Garantien. Der Inhalt dieses Papiers in Bezug auf Genauigkeit, Vollständigkeit oder Eignung der angegebenen Informationen entspricht den zum Zeitpunkt seiner Erstellung verfügbaren Quellen und sollte nicht als verlässlich angesehen werden, und die Wertpapierinhaber, Gläubiger oder andere Anteilseigner oder andere Personen dürfen sich nicht auf sie verlassen und ihnen keine Rechtsmittel oder Rechte darauf übertragen. <br><br>AFU lehnt jegliche Haftung für Schäden oder Verluste von Kapital, Zinsen oder Eigentum jeglicher Art (ob vorhersehbar oder nicht) ab, die durch ein Unternehmen oder eine Person entstehen könnten, das/die aufgrund von Informationen und Meinungen in Bezug auf AFU handelt, die in diesem Papier enthalten sind, oder aufgrund von anderen Informationen, die in Bezug auf weitere Untersuchungen vorgelegt werden. Die Informationen in diesem Whitepaper können ohne vorherige Ankündigung geändert werden. AFU ist nicht verpflichtet, die dargelegten Projektionen, Prognosen, Meinungen oder Schätzungen oder spätere Änderungen, die die Daten ungenau machen, zu aktualisieren, zu modifizieren oder zu verbessern. AFU und ihre Mitarbeiter oder Vertreter haben keine Haftung oder Verantwortung gegenüber einem Empfänger oder einer Person (sei es durch Fahrlässigkeit oder falsche Angaben oder aus Gründen der Vernunft). AFU übernimmt keine unabhängige Garantie für die in diesem Whitepaper dargestellten Informationen, einschließlich Projektionen, Aussichten und Prognosen. Jeder Empfänger oder jede Person muss sich ausschließlich auf seine eigenen Untersuchungen, Kenntnisse, Einschätzungen und Beurteilungen der Angelegenheit, die Gegenstand dieser Publikation ist, sowie auf alle anderen Informationen verlassen, die durch weitere Anfragen oder zur Befriedigung der Genauigkeit von Prognosen zur Verfügung gestellt werden. AFU hat alle Anstrengungen unternommen, um die Authentizität der in diesem Whitepaper enthaltenen Fakten und Prognosen zu gewährleisten. Alle Prognosen, Vorhersagen oder Pläne, die in dieser Whitepaper-Veröffentlichung erwähnt werden, können aufgrund verschiedener Risikofaktoren wie Marktvolatilität, rechtliche oder behördliche Exposition, Unternehmensmaßnahmen, Mängel in der Technologieentwicklung, Nichtverfügbarkeit von Informationen und alle anderen Risiken möglicherweise nicht erreicht werden. AFU kann Hyperlinks zu den Websites der in diesem Whitepaper vertretenen Unternehmen bereitstellen, wobei die Aufnahme eines Links nicht bedeutet, dass AFU Material auf der verlinkten Website empfiehlt, befürwortet oder billigt. Der Zugriff auf solche verlinkten Websites sollte ausschließlich auf eigenes Risiko erfolgen, und AFU übernimmt keinerlei Verantwortung für solches Material oder die Folgen davon. Dieses Whitepaper ist nur unter www.afuproject.com verfügbar und darf nicht reproduziert, weiterverbreitet oder an andere Stellen weitergegeben werden. Die Verbreitung dieses Whitepapers kann in bestimmten Ländern durch Vorschriften oder Gesetze eingeschränkt sein. Mit dem Zugriff auf diese Whitepaper-Publikation erklärt sich der Empfänger damit einverstanden, an die vorstehenden Einschränkungen gebunden zu sein.',
        summary: 'Das Projekt AFU wurde ins Leben gerufen, da sich bis anhin keine Kryptowährung durchsetzen konnte, welche den Profitgedanken der Kryptoinvestoren mit dem Gemeinnützigkeitsgedanken verbindet. AFU wurde von großen Tierfreunden gegründet und hat sich zum Ziel gesetzt, Kryptogeld in den Tier- und Artenschutz zu bringen.<br><br><h2>Use Cases</h2><ul><li>AFU fördert in erster Linie durch direkte Spenden und das monatliche Donation Voting den Tierschutz und den Wert des Tokens.</li><li>50% der über das Voting erhaltenen Tokens werden direkt verbrannt. Die anderen 50% wandern in den Charity Pool, um dessen Nachhaltigkeit sicherzustellen. 1% des Pools wird jeden Monat gemäss Donation Voting gespendet.</li><li>Unsere AFU Services (z.B. Werbung), welche wir den Charities bieten, können nur mit $AFU bezahlt werden.</li><li>Alleine der Tokenkauf fördert indirekt den Tierschutz, indem die erhaltenen Spenden einen höheren Wert erlangen. Das angestrebte Wachstum des Tokenwerts sowie die sorgfälige Auswahl und Zusammenarbeit mit unseren Partnern führt zu einer längeren Haltedauer der erhaltenen Spenden in $AFU.</li><li>AFU belohnt darüber hinaus die wichtigsten Spender mit Goodies (in Ausarbeitung).</li></ul><br>Neben der Wertsteigerung soll auch die <strong>Erwartung</strong> an eine Wertsteigerung des Tokens geschaffen werden. Dadurch werden einerseits Anreize für die Charities gesetzt, ihre Tokens nicht direkt nach Geldeingang wieder zu verkaufen. Zum Anderen bringt es die Möglichkeit, die eingegangenen Spendenbeträge durch das Halten der Tokens - zumindest bei längerer Haltedauer - substanziell zu vermehren. Ein nachhaltig hoher AFU Pool wird auch durch die AFU Services sichergestellt.',
        situationTitle: 'Ausgangslage',
        situation: '<h2>Kennzahlen</h2><ul><li>Es gibt keine globale Statistik über die totalen Spendensummen. Die Summe über die gröẞten Weltwirtschaften zeigt zumindest auf, dass das Gesamtvolumen bei mindestens mehreren Hundert Milliarden Dollar jährlich liegt.</li><li>Dabei ist weltweit die Gesamtsumme an Spenden 2019 im Vergleich zum Vorjahr um 4.1% angestiegen. Online-Spenden sind sogar um 12.1% gestiegen.</li><li>Millenials nutzen bereits heute den Online-Kanal für Spenden am meisten. Ein besonders starkes Wachstum ist bei mobilen Spenden zu erkennen. Im Rahmen der Online-Spenden wachsen Spenden im Umweltbereich besonders stark.</li></ul><a href="https://doublethedonation.com/tips/matching-grant-resources/nonprofit-fundraising-statistics/">Quelle</a><br><br><h2>Weitere Fakten</h2><ul><li>Millenials werden als die sozial verantwortlichsten Konsumenten definiert, denen verantwortungsbewusstes Handeln sehr wichtig ist. Deshalb spielt der soziale Aspekt für die Millenials eine besonders wichtige Rolle.</li><li>Millenials interessieren sich weniger für die Menschen oder die Ideen, die hinter einer Nonprofit-Organisation stehen, als vielmehr für die Ergebnisse, die die Nonprofit-Organisation produziert. Greifbare Ergebnisse sind wichtig.</li><li>Content Marketing, hauptsächlich durch Blogging und Social-Media-Beiträge, stellt für Organisationen eine wichtige Möglichkeit dar, sich mit ihren Gemeinschaften auseinanderzusetzen und ihre Online-Sichtbarkeit zu erhöhen.</li><li>Für kleine und mittlere Wohltätigkeitsorganisationen, die noch nicht so bekannt sind, ist der Online-Kanal besonders wichtig.</li></ul><a href="https://www.nptechforgood.com/2018/03/20/10-must-know-stats-about-online-fundraising/">Quelle</a><br><br><h2>Aktuelle Entwicklungen</h2><ul><li><strong>Mobile Spenden</strong>: Bereits oben erläutert</li><li><strong>Mikrospenden</strong>: stellen ein wichtiger Trend im Spendenmarkt dar. Wenn eine kleine Spende schnell und einfach gemacht werden kann, sind gerade Millenials deutlich gewillter zu spenden als wenn zuerst ein längeres Formular ausgefüllt werden muss. Bei Mikrospenden spielt auch der steuerliche Aspekt kaum eine Rolle (<a href="https://non-profit.today/micro-donations/">Source</a>)</li></ul><br><h2>Problemstellungen</h2>AFU möchte vor allem folgende Probleme angehen und lösen:<ul><li><strong>Spenden aus dem Kryptomarkt</strong>: Obwohl viele Investoren mit Bitcoin und anderen Kryptowährungen bereits viel Geld verdient haben und viele Millenials im Kryptomarkt aktiv sind, wird aus dem Kryptomarkt heute kaum etwas gespendet. Die Bereitschaft, einen kleinen Teil der eigenen Gewinne für einen guten Zweck zu spenden ist zwar da, aber es bestehen keine einfachen Möglichkeiten, die sich im Markt durchgesetzt haben, um effizient und wirkungsvoll zu spenden.</li><li><strong>Intransparenz</strong>: Was machen die Organisationen wirklich mit dem Geld? Welche sind vertrauenswürdig und erreichen wirklich etwas?</li><li><strong>Zeitmangel</strong>: Menschen, die helfen wollen, aber nicht die Zeit haben, zu spenden. Zeit ist etwas, das man nicht zurückbekommt und gerade Millenials haben immer zu wenig Zeit.</li><li><strong>Kurzfristige Spendeneinbrüche</strong>: 2020 war auch für viele Charities ein höchst aussergewöhnliches und herausforderndes Jahr. Kurzfristige Spendeneinbrüche verlangen nach neuen Kanälen und Lösungen.</li></ul>',
        approachTitle: 'Lösungsansatz',
        approach: '<h2>Vision</h2>Das Potenzial im Kryptomarkt zur Unterstützung von Tier- und Artenschutz soll voll ausgeschöpft werden. Wohltätigkeit und Profit sollen keine Gegensätze mehr sein, sondern Hand in Hand funktionieren.<br><br><h2>Mission</h2>Das im Kryptomarkt vorhandene Potenzial für Spenden an wohltätige Organisationen zum Zweck von Tier- und Artenschutz soll in AFU fliessen und dort direkt oder indirekt an geprüfte Organisationen weitergegeben werden. Die Organisationen sollen Anreize haben, die $AFU Tokens nicht sofort nach Geldeingang zu verkaufen sondern diese zu behalten. Der Tokenpreis soll nachhaltig ansteigen, um die eingegangenen Spenden zu vermehren, sodass noch mehr Gelder für die Organisationen zur Verfügung stehen. Das eingegangene Spendengeld soll nur solchen Organisationen zuflieẞen, welche einen minimalen Administrationsaufwand haben, sodass das meiste Geld direkt den Tieren zugute kommt.<br><br>Unsere Werte, mit denen wir zusammen mit der AFU Community unsere Mission verfolgen, werden auf der Homepage näher beschrieben.<br><br><h2>Zielgruppe</h2>Unsere Hauptzielgruppe sind Millenials. Bevorzugt werden Millenials, welche bereits eine Investition in eine Kryptowährung getätigt haben oder den Kryptomarkt kennen.<br><br>Spender, die nichts mit dem Kryptomarkt zu tun haben, werden weiterhin direkt Fiat an die Charities spenden. Wir möchten bestehende Kryptovermögen hin zu mehr Tierschutz bewegen und sehen es nicht als unsere Aufgabe, Fiatgeld in den Kryptomarkt zu bewegen. Dementsprechend fokussieren sich unsere Marketingaufwände auf den Kryptobereich.<br><br><h2>USP</h2>      <ul>        <li>Für bestehende Teilnehmer am Kryptomarkt bieten wir eine <strong>sehr einfache Lösung</strong>, einen Teil der Gewinne mit extrem geringem Aufwand und Kosten an eine <strong>geprüfte Charity</strong> zu spenden und dadurch direkt Tiere zu unterstützen. Investoren, welche kein Interesse an einer Spende haben, helfen mit dem Kauf von $AFU trotzdem mit, den Wert der Spenden zu erhöhen. <strong>Die Tierhilfe geht dadurch Hand in Hand mit dem Profitgedanken der Investoren</strong>.</li><li>AFU bietet dabei die Möglichkeit von <strong>Mikrospenden</strong>. Mit dem Aufbau auf dem TRON-Netzwerk gibt es keine nennenswerten Gebühren, sodass sich $AFU ideal auch für Mikrospenden eignet.</li><li>Nebst direkten Spenden bietet AFU den Investoren die Möglichkeit eines <strong>monatlichen Votings</strong>. Die Vermögen, welche das AFU Team monatlich aus dem Pool verteilt, werden gemäss Voting an die Partnerorganisationen verteilt. Wir glauben an den bottom-up Ansatz und binden unsere Community deshalb in diesen wichtigen Entscheid mit ein.</li><li>Unser Team fördert bei den Charities aktiv das Halten von $AFU auf der Wallet, statt die erhaltenen Spenden sofort wieder zu verkaufen. Dies wird unterstützt durch <strong>AFU-Services</strong> wie das Aufschalten von Werbung für Charities, was <strong>ausschlieẞlich mit $AFU bezahlt</strong> werden kann. Zudem können die erhaltenen Spendenbeiträge in Erwartung einer Preiserhöhung des AFU-Tokens <strong>durch Halten vermehrt</strong> werden.</li></ul><br>Durch unsere starke Präsenz und Vernetzung im Kryptomarkt sowie im Charity-Markt schützen wir uns vor Kopien.',
        utilities: 'Folgendes sind die wichtigsten Use Cases von $AFU:<br><br><ul><li><strong>Direkte Spenden</strong>: Ohne Middleman direkt den von uns geprüften Tier- und Artenschutzorganisationen spenden.</li><li><strong>Donation Voting</strong>: AFU spendet monatlich einen signifikanten Betrag aus dem AFU Pool an die Tierschutzorganisationen. Tokenholder können die favorisierte Organisation mittels einer Einzahlung von AFU in den Pool unterstützen und so die Ratio des gespendeten Gesamtbetrags zugunsten der gewählten Organisationen beeinflussen.</li><li><strong>Token burning</strong>: 50% der fürs Voting monatlich transferierten Token werden nach der Auszahlung der monatlichen Spende an die Charities geburnt. Der regelmässige Tokenburn unterstützt das Wachstum des Tokenwerts und führt zu höhere Spendenbeträgen und die Vermehrung der erhaltenen Spenden.</li><li><strong>Tokenkauf</strong>: Je höher die Marktkapitalisierung unserer Kryptowährung, desto höher sind die gespendeten Beiträge, welche die an uns angeschlossenen Charities ausgeschüttet werden. Dementsprechend liefert jeder Kauf von AFU einen Beitrag zu Tier- und Artenschutz.</li><li><strong>AFU Services</strong>: Gegenüber den Charities bieten wir unsere AFU Services an wie beispielsweise Werbekampagnen, die nur mit $AFU bezahlt werden können.</li></ul><br>Die gröẞten Spender erhalten auẞerdem kleine Goodies (mehr Informationen dazu folgen).',
        tokenomics: '<h2>Wert und Netzwerk</h2>$AFU ist ein Utility-Token. Der faire Wert kann daher nicht direkt berechnet werden und wird vom Markt bestimmt. $AFU ist ein TRC-10-Token. Wir sind blockchain-agnostic und behalten uns das Recht vor - falls sinnvoll und notwendig - den Token zu einem TRC-20 Token oder in ein anderes Netzwerk zu migrieren. Für die aktuellen Anwendungsfälle ist der TRC-10-Token ausreichend.<br><br><h2>Locked tokens</h2>15M Token sind im Charity Pool gesperrt und werden gemäß den oben beschriebenen Anwendungsfällen nur an Wohltätigkeitsorganisationen verteilt. 10M Tokens wurden als zusätzlicher direkter langfristiger Anreiz für einen höheren Tokenpreis für das Team gesperrt. Davon sind 5 Mio. bis zum 1. April 2021 gesperrt und weitere 5 Mio. bis zum 1. Oktober 2021.<br><br><h2>Tokenverteilung</h2>Vor der ersten Börsennotierung wurden die Tokens über OTC-Geschäfte (nur auf Einladung) zum Preis von 1 AFU = 1 TRX verteilt. Neben den 10 Millionen gesperrten Tokens für das Team mussten die Teammitglieder den Token kaufen. Es wurden bis auf kleine Giveaways mit einem Gesamtvolumen von unter 50000 Tokens keine Tokens kostenlos abgegeben. Die gesammelten Gelder werden für Entwicklung, Marketing, Börsennotierungen und Geschäftswachstum verwendet.',
      },
      footer: {
        section1: '$AFU Project',
        section1text: 'Das AFU-Team hat sich dem Ziel verschrieben, den Arten- und Tierschutz nicht nur auf dem heutigen Stand zu erhalten, sondern ihn zu verbessern. Für Krypto-Investoren ergänzt AFU den monetären Aspekt mit der gleichzeitigen Förderung des Natur- und Tierschutzes.',
        section1button: 'Whitepaper',
        section2: 'Links (coming soon)',
        section2item1: '$AFU kaufen',
        section2item2: 'CoinMarketCap',
        section2item3: 'Coingecko',
        section2item4: 'Whitepaper',
        section2item5: 'Impressum',
        section3: 'Impressum',
        section3text: 'Sebastian Wolf AFU<br />Hornstr. 8<br />54294 Trier<br />Germany',
        section3mails: 'hello@afuproject.com<br>business@afuproject.com',
        copyright: 'Alle Rechte vorbehalten &copy; 2020 Sebastian Wolf AFU',
      },
    },
  },
}

const i18n = new VueI18n({
  locale: localStorage.getItem('lang') === 'de' || localStorage.getItem('lang') === 'en' ? localStorage.getItem('lang') : navigator.language.split('-')[0] === 'de' ? 'de' : 'en', // set locale
  messages, // set locale messages
})

export default new Vuetify({
  lang: {
    t: (key, ...params) => i18n.t(key, params),
  },
  theme: {
    dark: false,
    themes: {
      light: {
        primary: '#7C6951',
        secondary: '#000000',
        accent: '#77654D',
      },
      dark: {
        primary: '#33313B',
        secondary: '#3C4F65',
        accent: '#834C69',
      },
    },
  },
})
